# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171109_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(max_length=30, verbose_name='时间'),
        ),
    ]
