# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Articles'),
        ),
    ]
